/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ActividadesEnClase;
/**
 *
 * @author Ikercito
 */
public class compraproducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(compraproducto.class.getName());

    /**
     * Creates new form compraproducto
     */
    public compraproducto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cabeza = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra De un Producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cabeza.setBackground(new java.awt.Color(204, 204, 255));
        Cabeza.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Cabeza.setForeground(new java.awt.Color(0, 0, 0));
        Cabeza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cabeza.setText("UNIVERSIDAD TECNICA DE MACHALA");
        Cabeza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cabeza.setOpaque(true);
        getContentPane().add(Cabeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 60));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 460, 70));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setBackground(new java.awt.Color(204, 204, 255));
        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setText("Producto:");
        lbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl1.setOpaque(true);
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 40));

        lbl2.setBackground(new java.awt.Color(204, 204, 255));
        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(0, 0, 0));
        lbl2.setText("Precio:");
        lbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl2.setOpaque(true);
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 40));

        lbl3.setBackground(new java.awt.Color(204, 204, 255));
        lbl3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setText("Cantidad:");
        lbl3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl3.setOpaque(true);
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, 40));

        txt2.setBackground(new java.awt.Color(255, 255, 255));
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 200, 40));

        txt1.setBackground(new java.awt.Color(255, 255, 255));
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 200, 40));

        txt3.setBackground(new java.awt.Color(255, 255, 255));
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 200, 40));

        btn1.setBackground(new java.awt.Color(204, 204, 255));
        btn1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 0, 0));
        btn1.setText("Comprar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn1KeyPressed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, -1));

        btn2.setBackground(new java.awt.Color(204, 204, 255));
        btn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 0, 0));
        btn2.setText("Nuevo");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn2KeyPressed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, -1));

        lbl4.setBackground(new java.awt.Color(204, 204, 255));
        lbl4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setText("Total a Pagar");
        lbl4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl4.setOpaque(true);
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 40));

        txt4.setBackground(new java.awt.Color(255, 255, 255));
        txt4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setEnabled(false);
        jPanel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        int cantidadd = Integer.parseInt(txt3.getText());
        double precioo = Double.parseDouble(txt2.getText());  
        double vtotal = cantidadd * precioo;
        txt4.setText(String.format("%.3f", vtotal));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txt1.setText(" ");
        txt2.setText(" ");
        txt3.setText(" ");
        txt4.setText(" ");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyPressed
        // TODO add your handling code here:
        int cantidadd = Integer.parseInt(txt3.getText());
        double precioo = Double.parseDouble(txt2.getText());  
        double vtotal = cantidadd * precioo;
        txt4.setText(String.format("%.3f", vtotal));
    }//GEN-LAST:event_btn1KeyPressed

    private void btn2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyPressed
        // TODO add your handling code here:
        txt1.setText(" ");
        txt2.setText(" ");
        txt3.setText(" ");
        txt4.setText(" ");
    }//GEN-LAST:event_btn2KeyPressed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new compraproducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cabeza;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
