package PROYECTO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.CardLayout;

/**
 *
 * @author LAB02_HS_MAQ11
 */
public class P_E19 extends javax.swing.JFrame {

    /**
     * Creates new form P_E19
     */
    public P_E19() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        P_Suma = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIngresoS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSerieS = new javax.swing.JTextArea();
        btnCalcularS = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        P_Multiplicacion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIngresoM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCalcularM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSerieM = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        txtIngresoM1 = new javax.swing.JTextField();
        P_Potencia = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIngresoP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIngresoP1 = new javax.swing.JTextField();
        btnCalcularP = new javax.swing.JButton();
        btnNuevoP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSerieP = new javax.swing.JTextArea();
        P_Factorial = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIngresoF = new javax.swing.JTextField();
        btnCalcularF = new javax.swing.JButton();
        BtnNuevoF = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSerieF = new javax.swing.JTextArea();
        P_Fibonacci = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtIngresoFi = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSerieFi = new javax.swing.JTextArea();
        btnNuevoFi = new javax.swing.JButton();
        P_Division = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtIngresoD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIngresoD2 = new javax.swing.JTextField();
        btnCalcularD = new javax.swing.JButton();
        btnNuevoD = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSerieD = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú para generar series de números y/o cálculos");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("UTMACH - IKER ARMIJOS -2025");
        jLabel2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(214, 214, 232));

        jButton1.setText("Sumar Números Naturales ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Multiplicación por sumas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Potencia Mediante Multiplicación");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Factorial");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Serie de Fibonacci");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("División Mediante Restas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addComponent(jButton4)
                .addGap(40, 40, 40)
                .addComponent(jButton5)
                .addGap(40, 40, 40)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.setBackground(new java.awt.Color(235, 235, 239));
        panelCentral.setLayout(new java.awt.CardLayout());

        P_Suma.setBackground(new java.awt.Color(232, 232, 255));

        jLabel3.setText("Ingresar N primeros numeros naturales: ");

        jLabel4.setText("Serie");

        txtSerieS.setColumns(20);
        txtSerieS.setRows(5);
        jScrollPane1.setViewportView(txtSerieS);

        btnCalcularS.setText("Calcular serie");
        btnCalcularS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSActionPerformed(evt);
            }
        });

        jButton7.setText("Nuevo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_SumaLayout = new javax.swing.GroupLayout(P_Suma);
        P_Suma.setLayout(P_SumaLayout);
        P_SumaLayout.setHorizontalGroup(
            P_SumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_SumaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_SumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIngresoS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(P_SumaLayout.createSequentialGroup()
                        .addComponent(btnCalcularS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        P_SumaLayout.setVerticalGroup(
            P_SumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_SumaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_SumaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularS)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        panelCentral.add(P_Suma, "E1");

        P_Multiplicacion.setBackground(new java.awt.Color(232, 232, 255));

        jLabel5.setText("Ingrese el primer numero");

        jLabel6.setText("Ingrese el segundo numero");

        btnCalcularM.setText("Calcular");
        btnCalcularM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularMActionPerformed(evt);
            }
        });

        txtSerieM.setColumns(20);
        txtSerieM.setRows(5);
        jScrollPane2.setViewportView(txtSerieM);

        jButton8.setText("Nuevo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_MultiplicacionLayout = new javax.swing.GroupLayout(P_Multiplicacion);
        P_Multiplicacion.setLayout(P_MultiplicacionLayout);
        P_MultiplicacionLayout.setHorizontalGroup(
            P_MultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MultiplicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_MultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoM)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoM1)
                    .addGroup(P_MultiplicacionLayout.createSequentialGroup()
                        .addComponent(btnCalcularM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        P_MultiplicacionLayout.setVerticalGroup(
            P_MultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MultiplicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoM1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_MultiplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularM)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        panelCentral.add(P_Multiplicacion, "E2");

        P_Potencia.setBackground(new java.awt.Color(232, 232, 255));

        jLabel7.setText("Ingrese la base");

        jLabel8.setText("Ingrese el exponente");

        btnCalcularP.setText("Calcular");
        btnCalcularP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPActionPerformed(evt);
            }
        });

        btnNuevoP.setText("Nuevo");
        btnNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPActionPerformed(evt);
            }
        });

        txtSerieP.setColumns(20);
        txtSerieP.setRows(5);
        jScrollPane3.setViewportView(txtSerieP);

        javax.swing.GroupLayout P_PotenciaLayout = new javax.swing.GroupLayout(P_Potencia);
        P_Potencia.setLayout(P_PotenciaLayout);
        P_PotenciaLayout.setHorizontalGroup(
            P_PotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_PotenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_PotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoP1)
                    .addGroup(P_PotenciaLayout.createSequentialGroup()
                        .addComponent(btnCalcularP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIngresoP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_PotenciaLayout.setVerticalGroup(
            P_PotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_PotenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_PotenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularP)
                    .addComponent(btnNuevoP))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panelCentral.add(P_Potencia, "E3");

        P_Factorial.setBackground(new java.awt.Color(232, 232, 255));

        jLabel9.setText("Ingrese un numero para calcular su factorial");

        btnCalcularF.setText("Calcular");
        btnCalcularF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFActionPerformed(evt);
            }
        });

        BtnNuevoF.setText("Nuevo");
        BtnNuevoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoFActionPerformed(evt);
            }
        });

        txtSerieF.setColumns(20);
        txtSerieF.setRows(5);
        jScrollPane4.setViewportView(txtSerieF);

        javax.swing.GroupLayout P_FactorialLayout = new javax.swing.GroupLayout(P_Factorial);
        P_Factorial.setLayout(P_FactorialLayout);
        P_FactorialLayout.setHorizontalGroup(
            P_FactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FactorialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_FactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoF)
                    .addGroup(P_FactorialLayout.createSequentialGroup()
                        .addComponent(btnCalcularF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(BtnNuevoF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        P_FactorialLayout.setVerticalGroup(
            P_FactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FactorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_FactorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularF)
                    .addComponent(BtnNuevoF))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        panelCentral.add(P_Factorial, "E4");

        P_Fibonacci.setBackground(new java.awt.Color(232, 232, 255));

        jLabel10.setText("Ingresar el limite de la serie fibonacci");

        jButton9.setText("Calcular Serie");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtSerieFi.setColumns(20);
        txtSerieFi.setRows(5);
        jScrollPane5.setViewportView(txtSerieFi);

        btnNuevoFi.setText("Nuevo");
        btnNuevoFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoFiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_FibonacciLayout = new javax.swing.GroupLayout(P_Fibonacci);
        P_Fibonacci.setLayout(P_FibonacciLayout);
        P_FibonacciLayout.setHorizontalGroup(
            P_FibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FibonacciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_FibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoFi)
                    .addGroup(P_FibonacciLayout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnNuevoFi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        P_FibonacciLayout.setVerticalGroup(
            P_FibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FibonacciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoFi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_FibonacciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(btnNuevoFi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        panelCentral.add(P_Fibonacci, "E5");

        P_Division.setBackground(new java.awt.Color(232, 232, 255));

        jLabel11.setText("Ingrese el primer numero");

        jLabel12.setText("Ingrese el segundo numero");

        btnCalcularD.setText("Calcular");
        btnCalcularD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDActionPerformed(evt);
            }
        });

        btnNuevoD.setText("Nuevo");
        btnNuevoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDActionPerformed(evt);
            }
        });

        txtSerieD.setColumns(20);
        txtSerieD.setRows(5);
        jScrollPane6.setViewportView(txtSerieD);

        javax.swing.GroupLayout P_DivisionLayout = new javax.swing.GroupLayout(P_Division);
        P_Division.setLayout(P_DivisionLayout);
        P_DivisionLayout.setHorizontalGroup(
            P_DivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_DivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoD)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIngresoD2)
                    .addGroup(P_DivisionLayout.createSequentialGroup()
                        .addComponent(btnCalcularD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnNuevoD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        P_DivisionLayout.setVerticalGroup(
            P_DivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_DivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresoD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(P_DivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularD)
                    .addComponent(btnNuevoD))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        panelCentral.add(P_Division, "E6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E1");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E2");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E3");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E4");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E5");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try 
        {
            CardLayout cl = (CardLayout)(panelCentral.getLayout());
            cl.show(panelCentral, "E6");
        }catch(Exception ex){}
        panelCentral.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCalcularSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSActionPerformed
        // TODO add your handling code here:
        int N = Integer.parseInt(txtIngresoS.getText());
        for (int i = 0; i <= N; i++)
        {
            txtSerieS.setText(txtSerieS.getText()+i*i);
            if(i<N)
            {
                txtSerieS.setText(txtSerieS.getText() + ", ");
            }
        }
    }//GEN-LAST:event_btnCalcularSActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        txtSerieS.setText("");
        txtIngresoS.setText("");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCalcularMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularMActionPerformed
        // TODO add your handling code here:
        double x1 = Double.parseDouble(txtIngresoM.getText());
        double x2 = Double.parseDouble(txtIngresoM1.getText());
        double producto = x1*x2;
        for (int i = 1; i<=x2; i++)
        {
            txtSerieM.setText(txtSerieM.getText()+ x1);
            if(i<x2)
            {
                txtSerieM.setText(txtSerieM.getText()+" + ");
            }
        }
        txtSerieM.setText(txtSerieM.getText()+ " = " + producto);
    }//GEN-LAST:event_btnCalcularMActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        txtSerieM.setText("");
        txtIngresoM.setText("");
        txtIngresoM1.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnCalcularPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPActionPerformed
        // TODO add your handling code here:
        double base = Double.parseDouble(txtIngresoP.getText());
        double exponente = Double.parseDouble(txtIngresoP1.getText());
        double potencia = (int) Math.pow(base, exponente);
        for(int i = 1; i <= exponente; i++)
        {
            txtSerieP.setText(txtSerieP.getText()+ base);
            if(i < exponente)
            {
                txtSerieP.setText(txtSerieP.getText()+ " * ");
            }
        }
        txtSerieP.setText(txtSerieP.getText()+ " = " + potencia);
    }//GEN-LAST:event_btnCalcularPActionPerformed

    private void btnNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPActionPerformed
        // TODO add your handling code here:
        txtSerieP.setText("");
        txtIngresoP.setText("");
        txtIngresoP1.setText("");
    }//GEN-LAST:event_btnNuevoPActionPerformed

    private void btnCalcularFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFActionPerformed
        // TODO add your handling code here:
        int fac = Integer.parseInt(txtIngresoF.getText());
        long factorial = 1;
        for (int i = 1; i <= fac; i++)
        {
            factorial *= i;
            
        }
        int j = fac;
        for (int i=1; i<=fac;i++)
        {
            j--;
            txtSerieF.setText(txtSerieF.getText() + (fac-j));
            if (i < fac)
            {
                txtSerieF.setText(txtSerieF.getText()+" * ");
            }
        }
        txtSerieF.setText(txtSerieF.getText() + " = " + factorial);
    }//GEN-LAST:event_btnCalcularFActionPerformed

    private void BtnNuevoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoFActionPerformed
        // TODO add your handling code here:
        txtSerieF.setText("");
        txtIngresoF.setText("");
    }//GEN-LAST:event_BtnNuevoFActionPerformed

    private void btnCalcularDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDActionPerformed
        // TODO add your handling code here:
        int x1 = Integer.parseInt(txtIngresoD.getText());
        int x2 = Integer.parseInt(txtIngresoD2.getText());
        int division = x1/x2;
        for (int i = x1; i>=1; i-=x2)
        {
            txtSerieD.setText(txtSerieD.getText()+ i);
            if(i>2)
            {
                txtSerieD.setText(txtSerieD.getText()+" - ");
            }
        }
        txtSerieD.setText(txtSerieD.getText()+ " = " + division);
    }//GEN-LAST:event_btnCalcularDActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int fibo = Integer.parseInt(txtIngresoFi.getText());
        int a=0, b=1;
        txtSerieFi.setText(txtSerieFi.getText() + a + " , " + b);
        for (int i = 2; i<=fibo; i++)
        {   
            int c = a+b;
            txtSerieFi.setText(txtSerieFi.getText()+ ", "+ c);
            a = b;
            b = c;
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnNuevoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDActionPerformed
        // TODO add your handling code here:
        txtSerieD.setText("");
        txtIngresoD.setText("");
        txtIngresoD2.setText("");
        
    }//GEN-LAST:event_btnNuevoDActionPerformed

    private void btnNuevoFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoFiActionPerformed
        // TODO add your handling code here:
        txtSerieFi.setText("");
        txtIngresoFi.setText("");
    }//GEN-LAST:event_btnNuevoFiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P_E19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P_E19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P_E19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P_E19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new P_E19().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNuevoF;
    private javax.swing.JPanel P_Division;
    private javax.swing.JPanel P_Factorial;
    private javax.swing.JPanel P_Fibonacci;
    private javax.swing.JPanel P_Multiplicacion;
    private javax.swing.JPanel P_Potencia;
    private javax.swing.JPanel P_Suma;
    private javax.swing.JButton btnCalcularD;
    private javax.swing.JButton btnCalcularF;
    private javax.swing.JButton btnCalcularM;
    private javax.swing.JButton btnCalcularP;
    private javax.swing.JButton btnCalcularS;
    private javax.swing.JButton btnNuevoD;
    private javax.swing.JButton btnNuevoFi;
    private javax.swing.JButton btnNuevoP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JTextField txtIngresoD;
    private javax.swing.JTextField txtIngresoD2;
    private javax.swing.JTextField txtIngresoF;
    private javax.swing.JTextField txtIngresoFi;
    private javax.swing.JTextField txtIngresoM;
    private javax.swing.JTextField txtIngresoM1;
    private javax.swing.JTextField txtIngresoP;
    private javax.swing.JTextField txtIngresoP1;
    private javax.swing.JTextField txtIngresoS;
    private javax.swing.JTextArea txtSerieD;
    private javax.swing.JTextArea txtSerieF;
    private javax.swing.JTextArea txtSerieFi;
    private javax.swing.JTextArea txtSerieM;
    private javax.swing.JTextArea txtSerieP;
    private javax.swing.JTextArea txtSerieS;
    // End of variables declaration//GEN-END:variables
}
